title: "Sonika Singhal"
description: "Ph.D. Candidate at VCU"
remote_theme: academicpages/academicpages.github.io@main

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar

# Navbar pages
include: ["_pages"]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true

paginate: 5
paginate_path: "/blog/page:num/"

markdown: kramdown
highlighter: rouge
