title: "Sonika Singhal"
email: "singhals3@vcu.edu"
description: >- 
  Ph.D. Candidate at VCU | Researcher in AI, Digital Platforms, and Cybersecurity
url: "https://sonika999.github.io"
github_username: sonika999
minimal_mistakes_skin: "default"
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Sonika Singhal"
  avatar: "/assets/img/profile.jpg"
  bio: "Ph.D. Candidate at Virginia Commonwealth University"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:singhals3@vcu.edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/sonika-singhal-53779924"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sonika999"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

collections:
  pages:
    output: true
    permalink: /:path/
